---
language: python
services: docker

env:
  global:
    - ROLE_NAME: apache
  matrix:
    - MOLECULE_DISTRO: debian9

install:
  # Install test dependencies.
  - pip install molecule docker

script:
  # Run tests.
  - molecule test
