---
- name: install pihole
  become: true
  command: bash "/tmp/Pi-hole/automated install/basic-install.sh" --unattended

- name: update filterlists
  command: pihole -g

- name: set password
  command: pihole -a -p "{{ web_password }}"
  when: install_web_server
